name: Setup Environment
description: Sets up Python environment and installs dependencies for Rayforge workflows
runs:
  using: composite
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"

    - name: Install build environment
      shell: bash
      run: |
        sudo apt update
        sudo apt install -y libcairo2-dev libgirepository1.0-dev gir1.2-gdkpixbuf-2.0 libvips42t64 gettext
        python3 -m pip install build --user

    - name: Install runtime dependencies
      shell: bash
      run: pip install --no-cache-dir -r requirements.txt

    - name: Install test dependencies
      shell: bash
      run: |
        pip install pytest pytest-asyncio pytest-mock pytest-cov
        pip install -ve . # Install rayforge in editable mode
