name: rayforge
version: git
adopt-info: rayforge
confinement: strict
base: core24

apps:
  rayforge:
    extensions: [gnome]
    command: bin/rayforge
    common-id: com.barebaric.rayforge
    desktop: share/applications/com.barebaric.rayforge.desktop
    plugs:
      - home
      - gsettings
      - network
      - network-bind
      - removable-media
      - x11
      - wayland
      - opengl
    environment:
      GI_TYPELIB_PATH: $SNAP/usr/lib/x86_64-linux-gnu/girepository-1.0
      PYTHONPATH: $SNAP/usr/lib/python3/dist-packages:$SNAP/lib/python3.10/site-packages
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/usr/lib/x86_64-linux-gnu/blas:$SNAP/usr/lib/x86_64-linux-gnu/lapack:$SNAP/usr/lib/$ARCH/libproxy

slots:
  rayforge:
    interface: dbus
    bus: session
    name: com.barebaric.rayforge

parts:
  rayforge:
    plugin: python
    source: .
    python-requirements:
      - requirements.txt
    build-packages:
      - python3-pip
      - python3-setuptools
      - git  # Required for git describe
    parse-info: [share/metainfo/com.barebaric.rayforge.metainfo.xml]
