name: rayforge
version: git
summary: A desktop application for laser cutting and engraving
description: |
  Rayforge is a desktop application designed for laser cutting
  and engraving. It provides an intuitive interface for users
  to create and manage their laser cutting projects.
confinement: strict
base: core24

apps:
  rayforge:
    extensions: [gnome]
    command: bin/rayforge
    plugs:
      - home
      - gsettings
      - network
      - network-bind
      - removable-media
      - x11
      - wayland
      - opengl
    environment:
      GI_TYPELIB_PATH: $SNAP/usr/lib/x86_64-linux-gnu/girepository-1.0
      PYTHONPATH: $SNAP/usr/lib/python3/dist-packages:$SNAP/lib/python3.10/site-packages
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/usr/lib/x86_64-linux-gnu/blas:$SNAP/usr/lib/x86_64-linux-gnu/lapack

slots:
  rayforge:
    interface: dbus
    bus: session
    name: com.barebaric.rayforge

parts:
  rayforge:
    plugin: python
    source: .
    python-requirements:
      - requirements.txt
    build-packages:
      - python3-dev
      - python3-pip
      - python3-setuptools
      - libgirepository1.0-dev
      - libcairo2-dev
      - libopencv-dev
      - libatlas-base-dev
      - libblas-dev
      - liblapack-dev
      - librsvg2-dev
      - git  # Required for git describe
    stage-packages:
      - python3
      - python3-gi
      - python3-numpy
      - python3-cairo
      - python3-opencv
      - gir1.2-gtk-3.0
      - gir1.2-adw-1
      - libgtk-3-0
      - libgirepository-1.0-1
      - libblas3
      - librsvg2-bin
      - libproxy1v5
    organize:
      data/com.barebaric.rayforge.desktop: share/applications/com.barebaric.rayforge.desktop
      data/com.barebaric.rayforge.metainfo.xml: share/metainfo/com.barebaric.rayforge.metainfo.xml
      data/com.barebaric.rayforge.svg: share/icons/hicolor/scalable/apps/com.barebaric.rayforge.svg
