name: rayforge
version: git
adopt-info: rayforge
confinement: strict
base: core24

apps:
  rayforge:
    extensions: [gnome]
    command: bin/rayforge
    common-id: com.barebaric.rayforge
    desktop: share/applications/com.barebaric.rayforge.desktop
    plugs:
      - home
      - gsettings
      - network
      - network-bind
      - removable-media
      - x11
      - wayland
      - opengl
      - camera
    environment:
      GI_TYPELIB_PATH: $SNAP/usr/lib/x86_64-linux-gnu/girepository-1.0
      PYTHONPATH: $SNAP/lib/python3.12/site-packages:$SNAP/usr/lib/python3/dist-packages
      LD_LIBRARY_PATH: $SNAP/gnome-platform/usr/lib/x86_64-linux-gnu/libproxy:$SNAP/usr/lib/x86_64-linux-gnu/libvips

slots:
  rayforge:
    interface: dbus
    bus: session
    name: com.barebaric.rayforge

parts:
  rayforge:
    plugin: python
    source: .
    python-requirements:
      - requirements.txt
    build-packages:
      - python3-pip
      - python3-setuptools
      - libvips-dev
      - git  # Required for git describe
    stage-packages:
      - libvips42t64
    parse-info: [share/metainfo/com.barebaric.rayforge.metainfo.xml]
    override-build: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/lib/x86_64-linux-gnu/libvips
      ln -s ../libvips.so.42 $SNAPCRAFT_PART_INSTALL/usr/lib/x86_64-linux-gnu/libvips/libvips.so.42
      ln -s ../libfftw3.so.3 $SNAPCRAFT_PART_INSTALL/usr/lib/x86_64-linux-gnu/libvips/libfftw3.so.3
      ln -s ../libcfitsio.so.10 $SNAPCRAFT_PART_INSTALL/usr/lib/x86_64-linux-gnu/libvips/libcfitsio.so.10
      ln -s ../libimagequant.so.0 $SNAPCRAFT_PART_INSTALL/usr/lib/x86_64-linux-gnu/libvips/libimagequant.so.0
      ln -s ../libcgif.so.0 $SNAPCRAFT_PART_INSTALL/usr/lib/x86_64-linux-gnu/libvips/libcgif.so.0
      ln -s ../libexif.so.12 $SNAPCRAFT_PART_INSTALL/usr/lib/x86_64-linux-gnu/libvips/libexif.so.12
      ln -s ../libspng.so.0 $SNAPCRAFT_PART_INSTALL/usr/lib/x86_64-linux-gnu/libvips/libspng.so.0
      ln -s ../libmatio.so.11 $SNAPCRAFT_PART_INSTALL/usr/lib/x86_64-linux-gnu/libvips/libmatio.so.11
      ln -s ../libOpenEXR-3_1.so.30 $SNAPCRAFT_PART_INSTALL/usr/lib/x86_64-linux-gnu/libvips/libOpenEXR-3_1.so.30
      ln -s ../libhwy.so.1 $SNAPCRAFT_PART_INSTALL/usr/lib/x86_64-linux-gnu/libvips/libhwy.so.1
      ln -s ../libhdf5_serial.so.103 $SNAPCRAFT_PART_INSTALL/usr/lib/x86_64-linux-gnu/libvips/libhdf5_serial.so.103
      ln -s ../libImath-3_1.so.29 $SNAPCRAFT_PART_INSTALL/usr/lib/x86_64-linux-gnu/libvips/libImath-3_1.so.29
      ln -s ../libIlmThread-3_1.so.30 $SNAPCRAFT_PART_INSTALL/usr/lib/x86_64-linux-gnu/libvips/libIlmThread-3_1.so.30
      ln -s ../libIex-3_1.so.30 $SNAPCRAFT_PART_INSTALL/usr/lib/x86_64-linux-gnu/libvips/libIex-3_1.so.30
      ln -s ../libsz.so.2 $SNAPCRAFT_PART_INSTALL/usr/lib/x86_64-linux-gnu/libvips/libsz.so.2
      ln -s ../libaec.so.0 $SNAPCRAFT_PART_INSTALL/usr/lib/x86_64-linux-gnu/libvips/libaec.so.0
      snapcraftctl build
