name: flake8 Lint

on: [push, pull_request]

jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: flake8 Lint
        uses: py-actions/flake8@v2
        with:
          ignore: E127,E128,E121,E123,E126,E226,E24,E704,W503,W504
          path: rayforge
