name: Build and Publish Wheel
on:
  repository_dispatch:
    types: [trigger-builds]

jobs:
  build-publish-wheel:
    name: Build and Publish Wheel for Rayforge
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write
    steps:
      - name: Setup environment
        uses: ./.github/actions/setup-environment

      - name: Build a wheel
        run: python3 -m build

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist
