name: Publish to PyPi
on: push

jobs:
  build-and-publish:
    name: Build and publish Rayforge to PyPI
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        fetch-tags: true

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"

    - name: Install build environment
      run: |
        sudo apt install libcairo2-dev libgirepository1.0-dev
        python3 -m pip install build --user

    - name: Install requirements
      run: pip install --no-cache-dir -r requirements.txt

    - name: Run pytest
      uses: pavelzw/pytest-action@v2
      with:
        verbose: true
        emoji: true
        job-summary: true
        click-to-expand: true
        report-title: 'PyTest Report'

    - name: Build a wheel
      run: python3 -m build

    - name: Publish package distributions to PyPI
      if: startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@release/v1
