name: Build and Publish Snap
on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  lint-test:
    uses: ./.github/workflows/lint-test.yml

  build-publish-snap:
    name: Build and Publish Snap
    needs: [lint-test]  # Run only if tests pass
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Compile Translations
        uses: ./.github/actions/compile-translations

      # This step is for development builds from the 'main' branch
      - name: Build snap (main branch)
        if: github.ref == 'refs/heads/main'
        uses: snapcore/action-build@v1
        id: build_main

      # This step is for release builds from tags
      - name: Build snap (tag release)
        if: startsWith(github.ref, 'refs/tags/')
        uses: snapcore/action-build@v1
        id: build_tag
        with:
          # Override the version in snapcraft.yaml with the exact tag name
          snapcraft-args: --override-version=${{ github.ref_name }}

      - name: Get snap name
        id: get_snap
        run: |
          # The snap name is needed by the next steps. Since only one of the build steps
          # will run, we check which one produced output and set it for subsequent steps.
          if [ -n "${{ steps.build_main.outputs.snap }}" ]; then
            echo "snap_path=${{ steps.build_main.outputs.snap }}" >> $GITHUB_OUTPUT
          else
            echo "snap_path=${{ steps.build_tag.outputs.snap }}" >> $GITHUB_OUTPUT
          fi

      - name: Test built snap
        run: |
          sudo snap install ${{ steps.get_snap.outputs.snap_path }} --dangerous
          rayforge --help

      - name: Publish to Snapcraft
        uses: snapcore/action-publish@v1
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.STORE_LOGIN }}
        with:
          snap: ${{ steps.get_snap.outputs.snap_path }}
          release: edge
