name: Publish to Snapcraft.io
on: push

jobs:
  build-and-publish:
    name: Build and publish Rayforge to Snapcraft.io
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true

    - uses: snapcore/action-build@v1
      id: build

    - uses: snapcore/action-publish@v1
      env:
        SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.STORE_LOGIN }}
      with:
        snap: ${{ steps.build.outputs.snap }}
        release: edge
